/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/charters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Charters */
        get: operations["list_charters_charters_get"];
        put?: never;
        /**
         * Post Charter
         * @description Wraps agentic_core.charter.create_charter exactly as
         *     scripts/set_charter.py does today -- the write itself happens inside
         *     that function's own SessionFactory session; `db` here is only used to
         *     read the persisted row back for the response, the same Component-1
         *     read pattern every GET route already uses.
         */
        post: operations["post_charter_charters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charters/{charter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Charter */
        get: operations["get_charter_charters__charter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charters/{charter_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Correct Charter
         * @description A correction inserts a NEW charter row (see agentic_core.charter.
         *     correct_charter's own docstring) -- 201, same as creation, because the
         *     id in this response is a different resource than charter_id, not an
         *     update to it.
         */
        post: operations["post_correct_charter_charters__charter_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charters/{charter_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Confirm Charter */
        post: operations["post_confirm_charter_charters__charter_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hypotheses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hypotheses */
        get: operations["list_hypotheses_hypotheses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hypotheses/{hypothesis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hypothesis */
        get: operations["get_hypothesis_hypotheses__hypothesis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-runs/{study_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Study Run
         * @description Component 5's poll target (docs/plans/stage-7-plan.md): the frontend
         *     hits this on an interval while status == 'running' and treats the
         *     transition to 'completed'/'failed' as the signal to stop polling and
         *     reveal the result.
         */
        get: operations["get_study_run_study_runs__study_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/study-runs/{study_run_id}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Study Run Traces */
        get: operations["get_study_run_traces_study_runs__study_run_id__traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verdicts/{verdict_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Verdict */
        get: operations["get_verdict_verdicts__verdict_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scoreboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scoreboard */
        get: operations["get_scoreboard_scoreboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BodyTerm
         * @description abs(open - close) — candle body size.
         */
        BodyTerm: {
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "body";
        };
        /**
         * Charter
         * @description ParsedCharter plus what code alone resolves. resolved_universe is
         *     never a field the LLM is asked to fill in -- there is no path by which
         *     a hallucinated ticker symbol can reach this object.
         */
        Charter: {
            parsed: components["schemas"]["ParsedCharter"];
            /** Resolved Universe */
            resolved_universe: string[];
            /**
             * Screening As Of
             * Format: date
             */
            screening_as_of: string;
            /** Screening Group Size */
            screening_group_size: number;
        };
        /** CharterCorrectIn */
        CharterCorrectIn: {
            /** Correction Text */
            correction_text: string;
        };
        /** CharterCreateIn */
        CharterCreateIn: {
            /** Mandate Text */
            mandate_text: string;
        };
        /** CharterOut */
        CharterOut: {
            /** Id */
            id: string;
            /** Mandate Text */
            mandate_text: string;
            charter: components["schemas"]["Charter"];
            /** Confirmed */
            confirmed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Parent Charter Id */
            parent_charter_id: string | null;
            /** Correction Round */
            correction_round: number;
            /** Correction Text */
            correction_text: string | null;
        };
        /**
         * CharterWriteOut
         * @description create_charter/correct_charter both return (id, Charter, blocked) --
         *     this is that third field, surfaced alongside the same row shape
         *     GET /charters/{id} already returns, rather than a differently-shaped
         *     response for writes vs. reads of the same resource.
         */
        CharterWriteOut: {
            /** Id */
            id: string;
            /** Mandate Text */
            mandate_text: string;
            charter: components["schemas"]["Charter"];
            /** Confirmed */
            confirmed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Parent Charter Id */
            parent_charter_id: string | null;
            /** Correction Round */
            correction_round: number;
            /** Correction Text */
            correction_text: string | null;
            /** Blocked */
            blocked: boolean;
        };
        /**
         * Claim
         * @description One quantitative statement in a verdict, bound to the tool call that
         *     produced it (.claude/rules/agent-honesty.md: "A claim with no valid
         *     reference is REJECTED").
         *
         *     metric is not in the shape agentic_core/db/models.py's column comment
         *     originally sketched, and it is the field that makes validation exact.
         *     Without it, checking `value` means matching against ANY numeric field in
         *     the referenced trace -- which would let a claim about sharpe_ratio
         *     validate against a p_value that happened to be numerically close, i.e.
         *     a fabricated claim passing because the wrong number agreed with it.
         */
        Claim: {
            /** Statement */
            statement: string;
            /** Tool Call Trace Id */
            tool_call_trace_id: number;
            /** Metric */
            metric: string;
            /** Value */
            value: number;
        };
        /** Comparison */
        Comparison: {
            /** Left */
            left: components["schemas"]["IndicatorTerm"] | components["schemas"]["PriceTerm"] | components["schemas"]["ConstantTerm"] | components["schemas"]["BodyTerm"] | components["schemas"]["MidpointTerm"] | components["schemas"]["RangeTerm"] | components["schemas"]["ScaledTerm"];
            /**
             * Op
             * @enum {string}
             */
            op: "gt" | "lt" | "gte" | "lte" | "crosses_above" | "crosses_below" | "eq_within";
            /** Right */
            right: components["schemas"]["IndicatorTerm"] | components["schemas"]["PriceTerm"] | components["schemas"]["ConstantTerm"] | components["schemas"]["BodyTerm"] | components["schemas"]["MidpointTerm"] | components["schemas"]["RangeTerm"] | components["schemas"]["ScaledTerm"];
            /** Tolerance */
            tolerance?: number | null;
        };
        /** Condition */
        Condition: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "and" | "or" | "leaf";
            comparison?: components["schemas"]["Comparison"] | null;
            /** Children */
            children?: components["schemas"]["Condition"][] | null;
        };
        /** ConstantTerm */
        ConstantTerm: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "constant";
            /** Value */
            value: number;
        };
        /**
         * EffectFamily
         * @description The effect families docs/architecture.md names as the ones a handful
         *     of curated papers can cover ("only a few dozen effect families...
         *     momentum, mean-reversion, low-volatility, value, quality, seasonality").
         *
         *     This is exactly the closed set ParsedCharter.hypothesis_families offers
         *     her -- "methodology" is deliberately NOT a member here, even though the
         *     corpus also holds methodology papers (Component 3): "investigate
         *     methodology" is not something a research mandate would ever ask for,
         *     since methodology papers ground the system's own statistical rigor
         *     (the multiple-comparisons correction), not a hypothesis family to test.
         *     See CorpusEffectFamily below for the corpus's own, slightly wider tag set.
         * @enum {string}
         */
        EffectFamily: "momentum" | "mean_reversion" | "low_volatility" | "value" | "quality" | "seasonality";
        /**
         * FalsificationCondition
         * @description Pre-registered BEFORE any testing (.claude/rules/agent-honesty.md) --
         *     deliberately single-clause, not a compound and/or tree the way entry/
         *     exit conditions are: pre-registration integrity benefits from staying
         *     simple, and a compound condition is exactly the kind of thing that could
         *     quietly grow wiggle room later. metric's vocabulary is drawn directly
         *     from BacktestResult's and SignificanceResult's real field names
         *     (backtester/result.py, research_stats/significance.py) so Component 7
         *     can mechanically evaluate this against whatever result object it
         *     actually has, with no name mismatch possible.
         *
         *     This is the hypothesis's OWN pre-registered bar, separate from Component
         *     7's multiple-comparisons-corrected significance threshold (which
         *     adjusts for how many hypotheses have been tested under the charter, plus
         *     a stricter multiplier for grounding: none) -- two different mechanisms
         *     applied at two different points, not overlapping.
         */
        FalsificationCondition: {
            /**
             * Metric
             * @enum {string}
             */
            metric: "sharpe_ratio" | "annual_return_pct" | "total_return_pct" | "max_drawdown_pct" | "win_rate_pct" | "p_value";
            /**
             * Comparison
             * @enum {string}
             */
            comparison: "less_than" | "greater_than";
            /** Threshold */
            threshold: number;
        };
        /**
         * GroundingChunk
         * @description One retrieved piece of evidence, from either tier -- a unified shape
         *     so Component 4 can build a hypothesis's citations the same way
         *     regardless of which tier actually fired. paper_id is only ever set for
         *     local_corpus (Tier 1 knows exactly which curated paper a chunk came
         *     from); url is only ever set for whitelist_search (Tier 2 is live web
         *     search, with no curated paper_id to point at). relevance is comparable
         *     within a tier, not necessarily across tiers -- see ground_topic's own
         *     module docstring for why.
         */
        GroundingChunk: {
            /**
             * Source
             * @enum {string}
             */
            source: "local_corpus" | "whitelist_search";
            /** Title */
            title: string;
            /** Text */
            text: string;
            /** Relevance */
            relevance: number;
            /** Paper Id */
            paper_id?: string | null;
            /** Url */
            url?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HypothesisOut */
        HypothesisOut: {
            /** Id */
            id: string;
            /** Charter Id */
            charter_id: string;
            rule: components["schemas"]["StrategyRule"];
            /** Prediction */
            prediction: string;
            falsification_condition: components["schemas"]["FalsificationCondition"];
            /** Rationale */
            rationale: string;
            /** Citations */
            citations: components["schemas"]["GroundingChunk"][];
            /** Grounding Tier */
            grounding_tier: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Study Run Id */
            study_run_id: string | null;
        };
        /** IndicatorTerm */
        IndicatorTerm: {
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "indicator";
            /** Name */
            name: string;
            /** Params */
            params?: {
                [key: string]: number;
            };
        };
        /**
         * MidpointTerm
         * @description (open + close) / 2 — candle body midpoint.
         */
        MidpointTerm: {
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "midpoint";
        };
        /**
         * ParsedCharter
         * @description Exactly what llm_client.structured_output is asked to produce from
         *     her mandate text. No ticker symbols, no resolved data of any kind --
         *     only fields whose fuzziness is the sanctioned kind (translating her
         *     sentence into structure), per docs/architecture.md's "vagueness stops
         *     at the human boundary."
         */
        ParsedCharter: {
            universe: components["schemas"]["UniverseFilter"];
            /** Hypothesis Families */
            hypothesis_families: components["schemas"]["EffectFamily"][];
            /**
             * Timeframe
             * @default daily
             * @enum {string}
             */
            timeframe: "daily" | "weekly" | "monthly";
            /** History Start */
            history_start?: string | null;
            /**
             * Scoring Preference
             * @default balanced
             * @enum {string}
             */
            scoring_preference: "robustness" | "raw_returns" | "balanced";
        };
        /** PriceTerm */
        PriceTerm: {
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "price";
            /**
             * Field
             * @enum {string}
             */
            field: "open" | "high" | "low" | "close" | "volume";
        };
        /**
         * RangeTerm
         * @description high - low — full bar range.
         */
        RangeTerm: {
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "range";
        };
        /**
         * ScaledTerm
         * @description Any other term multiplied by a positive constant, e.g. half of today's range.
         */
        ScaledTerm: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "scaled";
            /** Term */
            term: components["schemas"]["IndicatorTerm"] | components["schemas"]["PriceTerm"] | components["schemas"]["ConstantTerm"] | components["schemas"]["BodyTerm"] | components["schemas"]["MidpointTerm"] | components["schemas"]["RangeTerm"] | components["schemas"]["ScaledTerm"];
            /** Factor */
            factor: number;
        };
        /** ScoreboardConfirmedEntry */
        ScoreboardConfirmedEntry: {
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Charter Id */
            charter_id: string;
            verdict: components["schemas"]["VerdictOut"];
        };
        /** ScoreboardOut */
        ScoreboardOut: {
            /** Confirmed */
            confirmed: components["schemas"]["ScoreboardConfirmedEntry"][];
            /** Decayed */
            decayed: components["schemas"]["ScoreboardConfirmedEntry"][];
            /** Decayed Note */
            decayed_note: string;
            /** Testing */
            testing: components["schemas"]["ScoreboardTestingEntry"][];
        };
        /** ScoreboardTestingEntry */
        ScoreboardTestingEntry: {
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Charter Id */
            charter_id: string;
            /** Study Run Id */
            study_run_id: string | null;
        };
        /** StrategyRule */
        StrategyRule: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Literature Source */
            literature_source?: string | null;
            entry: components["schemas"]["Condition"];
            exit?: components["schemas"]["Condition"] | null;
            /** Exit After Bars */
            exit_after_bars?: number | null;
        };
        /** StudyRunOut */
        StudyRunOut: {
            /** Id */
            id: string;
            /** Hypothesis Id */
            hypothesis_id: string;
            /** Study Design Id */
            study_design_id: string;
            /** Status */
            status: string;
            /** Step Count */
            step_count: number;
            /** Failure Reason */
            failure_reason: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Verdict Id */
            verdict_id: string | null;
        };
        /** ToolCallTraceOut */
        ToolCallTraceOut: {
            /** Id */
            id: number;
            /** Study Run Id */
            study_run_id: string;
            /** Step Index */
            step_index: number;
            /** Window Index */
            window_index: number;
            /** Tool Name */
            tool_name: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Is Error */
            is_error: boolean;
            /**
             * Called At
             * Format: date-time
             */
            called_at: string;
        };
        /**
         * UniverseFilter
         * @description What screen_universe (Stage 4) needs to resolve a real ticker list.
         *
         *     cut is a closed vocabulary, not a raw percentile float, on purpose --
         *     .claude/rules/data-pipeline.md requires relative, never hand-picked,
         *     thresholds. Code (agentic_core.charter.CUT_TO_PERCENTILE) maps each
         *     name to a fixed percentile; the LLM never emits a number here.
         */
        UniverseFilter: {
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
            /**
             * Metric
             * @default liquidity
             * @enum {string}
             */
            metric: "liquidity" | "volatility";
            /**
             * Cut
             * @default quintile
             * @enum {string}
             */
            cut: "quintile" | "tercile" | "decile";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerdictOut */
        VerdictOut: {
            /** Id */
            id: string;
            /** Study Run Id */
            study_run_id: string;
            /** Status */
            status: string;
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Hypothesis Count Under Charter */
            hypothesis_count_under_charter: number;
            /** Corrected Significance Threshold */
            corrected_significance_threshold: number;
            /** Narrative */
            narrative: string;
            /** Caveats */
            caveats: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_charters_charters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharterOut"][];
                };
            };
        };
    };
    post_charter_charters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharterCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharterWriteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_charter_charters__charter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                charter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_correct_charter_charters__charter_id__correct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                charter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharterCorrectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharterWriteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_confirm_charter_charters__charter_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                charter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hypotheses_hypotheses_get: {
        parameters: {
            query: {
                charter_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hypothesis_hypotheses__hypothesis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hypothesis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HypothesisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_study_run_study_runs__study_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_study_run_traces_study_runs__study_run_id__traces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                study_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolCallTraceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_verdict_verdicts__verdict_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verdict_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoreboard_scoreboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreboardOut"];
                };
            };
        };
    };
}
