"""Extended-tier indicator registry -- AUTO-GENERATED, do not hand-edit.

Produced by `scripts/generate_extended_indicators.py` (structure + LLM-proposed
parameter bounds) and rewritten in place by `scripts/verify_extended_indicators.py`
(flips verified/verified_on/lib_version per entry after execution-based checks). To
regenerate from scratch, rerun both scripts in that order.
"""

from datetime import date

import pandas_ta as ta

from .indicators import IndicatorSpec

EXTENDED_INDICATORS: dict[str, IndicatorSpec] = {
    "ABER_ATR": IndicatorSpec(
        fn=ta.aberration,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'atr_length': (2.0, 500.0)},
        column_prefix='ABER_ATR_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "ABER_SG": IndicatorSpec(
        fn=ta.aberration,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'atr_length': (2.0, 500.0)},
        column_prefix='ABER_SG_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ABER_XG": IndicatorSpec(
        fn=ta.aberration,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'atr_length': (2.0, 500.0)},
        column_prefix='ABER_XG_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ABER_ZG": IndicatorSpec(
        fn=ta.aberration,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'atr_length': (2.0, 500.0)},
        column_prefix='ABER_ZG_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "ACCBL": IndicatorSpec(
        fn=ta.accbands,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'c': (0.0, 10.0), 'drift': (0.0, 10.0)},
        column_prefix='ACCBL_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "ACCBM": IndicatorSpec(
        fn=ta.accbands,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'c': (0.0, 10.0), 'drift': (0.0, 10.0)},
        column_prefix='ACCBM_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "ACCBU": IndicatorSpec(
        fn=ta.accbands,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'c': (0.0, 10.0), 'drift': (0.0, 10.0)},
        column_prefix='ACCBU_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "ADOSC": IndicatorSpec(
        fn=ta.adosc,
        inputs=('high', 'low', 'close', 'volume'),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 500.0)},
        column_prefix=None,
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "AGJ": IndicatorSpec(
        fn=ta.alligator,
        inputs=('close',),
        params={'jaw': (2.0, 500.0), 'teeth': (2.0, 500.0), 'lips': (2.0, 500.0)},
        column_prefix='AGj_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "AGL": IndicatorSpec(
        fn=ta.alligator,
        inputs=('close',),
        params={'jaw': (2.0, 500.0), 'teeth': (2.0, 500.0), 'lips': (2.0, 500.0)},
        column_prefix='AGl_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "AGT": IndicatorSpec(
        fn=ta.alligator,
        inputs=('close',),
        params={'jaw': (2.0, 500.0), 'teeth': (2.0, 500.0), 'lips': (2.0, 500.0)},
        column_prefix='AGt_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "ALMA": IndicatorSpec(
        fn=ta.alma,
        inputs=('close',),
        params={'length': (2.0, 500.0), 'sigma': (0.1, 100.0), 'dist_offset': (0.0, 1.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "ALPHAT": IndicatorSpec(
        fn=ta.alphatrend,
        inputs=('open', 'high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'multiplier': (0.1, 100.0), 'threshold': (0.0, 100.0), 'lag': (0.0, 50.0)},
        column_prefix='ALPHAT_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "ALPHATL": IndicatorSpec(
        fn=ta.alphatrend,
        inputs=('open', 'high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'multiplier': (0.1, 100.0), 'threshold': (0.0, 100.0), 'lag': (0.0, 50.0)},
        column_prefix='ALPHATl_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "AMATE_LR": IndicatorSpec(
        fn=ta.amat,
        inputs=('close',),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 500.0), 'lookback': (2.0, 500.0)},
        column_prefix='AMATe_LR_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "AMATE_SR": IndicatorSpec(
        fn=ta.amat,
        inputs=('close',),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 500.0), 'lookback': (2.0, 500.0)},
        column_prefix='AMATe_SR_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "AO": IndicatorSpec(
        fn=ta.ao,
        inputs=('high', 'low'),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 500.0)},
        column_prefix=None,
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "APO": IndicatorSpec(
        fn=ta.apo,
        inputs=('close',),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 500.0)},
        column_prefix=None,
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "AR": IndicatorSpec(
        fn=ta.brar,
        inputs=('open', 'high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'scalar': (1.0, 100.0), 'drift': (0.0, 10.0)},
        column_prefix='AR_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "AROOND": IndicatorSpec(
        fn=ta.aroon,
        inputs=('high', 'low'),
        params={'length': (2.0, 500.0), 'scalar': (1.0, 100.0)},
        column_prefix='AROOND_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "AROONOSC": IndicatorSpec(
        fn=ta.aroon,
        inputs=('high', 'low'),
        params={'length': (2.0, 500.0), 'scalar': (1.0, 100.0)},
        column_prefix='AROONOSC_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "AROONU": IndicatorSpec(
        fn=ta.aroon,
        inputs=('high', 'low'),
        params={'length': (2.0, 500.0), 'scalar': (1.0, 100.0)},
        column_prefix='AROONU_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ATRTS": IndicatorSpec(
        fn=ta.atrts,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'ma_length': (2.0, 500.0), 'k': (0.1, 10.0), 'drift': (0.0, 10.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "BEARP": IndicatorSpec(
        fn=ta.eri,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 100.0)},
        column_prefix='BEARP_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "BIAS": IndicatorSpec(
        fn=ta.bias,
        inputs=('close',),
        params={'length': (2.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "BOP": IndicatorSpec(
        fn=ta.bop,
        inputs=('open', 'high', 'low', 'close'),
        params={'scalar': (1.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "BR": IndicatorSpec(
        fn=ta.brar,
        inputs=('open', 'high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'scalar': (1.0, 100.0), 'drift': (0.0, 10.0)},
        column_prefix='BR_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "BULLP": IndicatorSpec(
        fn=ta.eri,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 100.0)},
        column_prefix='BULLP_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "CDL_DOJI_10_0.1": IndicatorSpec(
        fn=ta.cdl_pattern,
        inputs=('open', 'high', 'low', 'close'),
        params={'scalar': (1.0, 100.0)},
        column_prefix='CDL_DOJI_10_0.1',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "CDL_INSIDE": IndicatorSpec(
        fn=ta.cdl_pattern,
        inputs=('open', 'high', 'low', 'close'),
        params={'scalar': (1.0, 100.0)},
        column_prefix='CDL_INSIDE',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "CFO": IndicatorSpec(
        fn=ta.cfo,
        inputs=('close',),
        params={'length': (2.0, 500.0), 'scalar': (1.0, 100.0), 'drift': (0.0, 10.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "CG": IndicatorSpec(
        fn=ta.cg,
        inputs=('close',),
        params={'length': (2.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "CHDLREXTD": IndicatorSpec(
        fn=ta.chandelier_exit,
        inputs=('high', 'low', 'close'),
        params={'high_length': (2.0, 500.0), 'low_length': (2.0, 500.0), 'atr_length': (2.0, 500.0), 'multiplier': (0.1, 10.0), 'drift': (0.0, 10.0)},
        column_prefix='CHDLREXTd_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "CHDLREXTL": IndicatorSpec(
        fn=ta.chandelier_exit,
        inputs=('high', 'low', 'close'),
        params={'high_length': (2.0, 500.0), 'low_length': (2.0, 500.0), 'atr_length': (2.0, 500.0), 'multiplier': (0.1, 10.0), 'drift': (0.0, 10.0)},
        column_prefix='CHDLREXTl_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "CHDLREXTS": IndicatorSpec(
        fn=ta.chandelier_exit,
        inputs=('high', 'low', 'close'),
        params={'high_length': (2.0, 500.0), 'low_length': (2.0, 500.0), 'atr_length': (2.0, 500.0), 'multiplier': (0.1, 10.0), 'drift': (0.0, 10.0)},
        column_prefix='CHDLREXTs_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "CHOP": IndicatorSpec(
        fn=ta.chop,
        inputs=('high', 'low', 'close'),
        params={'length': (5.0, 100.0), 'atr_length': (1.0, 50.0), 'scalar': (0.1, 100.0), 'drift': (0.0, 10.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "CKSPL": IndicatorSpec(
        fn=ta.cksp,
        inputs=('high', 'low', 'close'),
        params={'p': (1.0, 50.0), 'x': (0.1, 5.0), 'q': (1.0, 50.0)},
        column_prefix='CKSPl_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "CKSPS": IndicatorSpec(
        fn=ta.cksp,
        inputs=('high', 'low', 'close'),
        params={'p': (1.0, 50.0), 'x': (0.1, 5.0), 'q': (1.0, 50.0)},
        column_prefix='CKSPs_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "CLOSE_Z": IndicatorSpec(
        fn=ta.cdl_z,
        inputs=('open', 'high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'ddof': (0.0, 2.0)},
        column_prefix='close_Z_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "CMF": IndicatorSpec(
        fn=ta.cmf,
        inputs=('high', 'low', 'close', 'volume'),
        params={'length': (5.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "CMO": IndicatorSpec(
        fn=ta.cmo,
        inputs=('close',),
        params={'length': (2.0, 100.0), 'scalar': (0.1, 100.0), 'drift': (0.0, 10.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "COPPOCK": IndicatorSpec(
        fn=ta.coppock,
        inputs=('close',),
        params={'length': (5.0, 200.0), 'fast': (2.0, 50.0), 'slow': (2.0, 100.0)},
        column_prefix=None,
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "CRSI": IndicatorSpec(
        fn=ta.crsi,
        inputs=('close',),
        params={'rsi_length': (2.0, 50.0), 'streak_length': (1.0, 30.0), 'rank_length': (1.0, 100.0), 'scalar': (0.1, 100.0), 'drift': (0.0, 10.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "CTI": IndicatorSpec(
        fn=ta.cti,
        inputs=('close',),
        params={'length': (2.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "D": IndicatorSpec(
        fn=ta.kdj,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 100.0), 'signal': (1.0, 50.0)},
        column_prefix='D_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "DCL": IndicatorSpec(
        fn=ta.donchian,
        inputs=('high', 'low'),
        params={'lower_length': (1.0, 100.0), 'upper_length': (1.0, 100.0)},
        column_prefix='DCL_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "DCM": IndicatorSpec(
        fn=ta.donchian,
        inputs=('high', 'low'),
        params={'lower_length': (1.0, 100.0), 'upper_length': (1.0, 100.0)},
        column_prefix='DCM_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "DCU": IndicatorSpec(
        fn=ta.donchian,
        inputs=('high', 'low'),
        params={'lower_length': (1.0, 100.0), 'upper_length': (1.0, 100.0)},
        column_prefix='DCU_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "DECAY": IndicatorSpec(
        fn=ta.decay,
        inputs=('close',),
        params={'length': (1.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "DECREASING": IndicatorSpec(
        fn=ta.decreasing,
        inputs=('close',),
        params={'length': (1.0, 100.0), 'percent': (0.0, 100.0), 'drift': (0.0, 10.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "EBSW": IndicatorSpec(
        fn=ta.ebsw,
        inputs=('close',),
        params={'length': (2.0, 100.0), 'bars': (1.0, 50.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "EFI": IndicatorSpec(
        fn=ta.efi,
        inputs=('close', 'volume'),
        params={'length': (2.0, 100.0), 'drift': (0.0, 10.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ENTROPY": IndicatorSpec(
        fn=ta.entropy,
        inputs=('close',),
        params={'length': (2.0, 100.0), 'base': (1.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "EOM": IndicatorSpec(
        fn=ta.eom,
        inputs=('high', 'low', 'close', 'volume'),
        params={'length': (2.0, 100.0), 'divisor': (1.0, 100.0), 'drift': (0.0, 10.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ER": IndicatorSpec(
        fn=ta.er,
        inputs=('close',),
        params={'length': (2.0, 100.0), 'drift': (0.0, 10.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "EXHC_DNA": IndicatorSpec(
        fn=ta.exhc,
        inputs=('close',),
        params={'length': (2.0, 100.0), 'cap': (1.0, 100.0)},
        column_prefix='EXHC_DNa',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "EXHC_UPA": IndicatorSpec(
        fn=ta.exhc,
        inputs=('close',),
        params={'length': (2.0, 100.0), 'cap': (1.0, 100.0)},
        column_prefix='EXHC_UPa',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "FAMA": IndicatorSpec(
        fn=ta.mama,
        inputs=('close',),
        params={'fastlimit': (0.01, 1.0), 'slowlimit': (0.01, 1.0), 'prenan': (0.0, 1.0)},
        column_prefix='FAMA_',
        cross_check={'type': 'greater_than', 'left': 'fastlimit', 'right': 'slowlimit'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "FISHERT": IndicatorSpec(
        fn=ta.fisher,
        inputs=('high', 'low'),
        params={'length': (2.0, 100.0), 'signal': (1.0, 50.0)},
        column_prefix='FISHERT_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "FISHERTS": IndicatorSpec(
        fn=ta.fisher,
        inputs=('high', 'low'),
        params={'length': (2.0, 100.0), 'signal': (1.0, 50.0)},
        column_prefix='FISHERTs_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HA_CLOSE": IndicatorSpec(
        fn=ta.ha,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='HA_close',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HA_HIGH": IndicatorSpec(
        fn=ta.ha,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='HA_high',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HA_LOW": IndicatorSpec(
        fn=ta.ha,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='HA_low',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HA_OPEN": IndicatorSpec(
        fn=ta.ha,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='HA_open',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HIGH_Z": IndicatorSpec(
        fn=ta.cdl_z,
        inputs=('open', 'high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'ddof': (0.0, 2.0)},
        column_prefix='high_Z_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HILO": IndicatorSpec(
        fn=ta.hilo,
        inputs=('high', 'low', 'close'),
        params={'high_length': (2.0, 100.0), 'low_length': (2.0, 100.0)},
        column_prefix='HILO_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HILOL": IndicatorSpec(
        fn=ta.hilo,
        inputs=('high', 'low', 'close'),
        params={'high_length': (2.0, 100.0), 'low_length': (2.0, 100.0)},
        column_prefix='HILOl_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HILOS": IndicatorSpec(
        fn=ta.hilo,
        inputs=('high', 'low', 'close'),
        params={'high_length': (2.0, 100.0), 'low_length': (2.0, 100.0)},
        column_prefix='HILOs_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HL2": IndicatorSpec(
        fn=ta.hl2,
        inputs=('high', 'low'),
        params={},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HLC3": IndicatorSpec(
        fn=ta.hlc3,
        inputs=('high', 'low', 'close'),
        params={},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HT_TRENDLINE": IndicatorSpec(
        fn=ta.ht_trendline,
        inputs=('close',),
        params={'prenan': (0.0, 1.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "HWL": IndicatorSpec(
        fn=ta.hwc,
        inputs=('close',),
        params={'scalar': (0.1, 10.0), 'na': (1.0, 50.0), 'nb': (1.0, 50.0), 'nc': (1.0, 50.0), 'nd': (1.0, 50.0)},
        column_prefix='HWL_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "HWM": IndicatorSpec(
        fn=ta.hwc,
        inputs=('close',),
        params={'scalar': (0.1, 10.0), 'na': (1.0, 50.0), 'nb': (1.0, 50.0), 'nc': (1.0, 50.0), 'nd': (1.0, 50.0)},
        column_prefix='HWM_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "HWMA": IndicatorSpec(
        fn=ta.hwma,
        inputs=('close',),
        params={'na': (1.0, 50.0), 'nb': (1.0, 50.0), 'nc': (1.0, 50.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "HWPCT": IndicatorSpec(
        fn=ta.hwc,
        inputs=('close',),
        params={'scalar': (0.1, 10.0), 'na': (1.0, 50.0), 'nb': (1.0, 50.0), 'nc': (1.0, 50.0), 'nd': (1.0, 50.0)},
        column_prefix='HWPCT_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "HWU": IndicatorSpec(
        fn=ta.hwc,
        inputs=('close',),
        params={'scalar': (0.1, 10.0), 'na': (1.0, 50.0), 'nb': (1.0, 50.0), 'nc': (1.0, 50.0), 'nd': (1.0, 50.0)},
        column_prefix='HWU_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "HWW": IndicatorSpec(
        fn=ta.hwc,
        inputs=('close',),
        params={'scalar': (0.1, 10.0), 'na': (1.0, 50.0), 'nb': (1.0, 50.0), 'nc': (1.0, 50.0), 'nd': (1.0, 50.0)},
        column_prefix='HWW_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "INCREASING": IndicatorSpec(
        fn=ta.increasing,
        inputs=('close',),
        params={'length': (1.0, 100.0), 'percent': (0.0, 100.0), 'drift': (0.0, 1.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "INERTIA": IndicatorSpec(
        fn=ta.inertia,
        inputs=('close',),
        params={'length': (2.0, 100.0), 'rvi_length': (2.0, 100.0), 'scalar': (0.1, 100.0), 'drift': (0.0, 1.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "J": IndicatorSpec(
        fn=ta.kdj,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 100.0), 'signal': (1.0, 50.0)},
        column_prefix='J_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "JMA": IndicatorSpec(
        fn=ta.jma,
        inputs=('close',),
        params={'length': (2.0, 200.0), 'phase': (-100.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "K": IndicatorSpec(
        fn=ta.kdj,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 100.0), 'signal': (1.0, 50.0)},
        column_prefix='K_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "KAMA": IndicatorSpec(
        fn=ta.kama,
        inputs=('close',),
        params={'length': (2.0, 200.0), 'fast': (1.0, 50.0), 'slow': (10.0, 100.0)},
        column_prefix=None,
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "KCBE": IndicatorSpec(
        fn=ta.kc,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 100.0), 'scalar': (0.1, 10.0)},
        column_prefix='KCBe_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "KCLE": IndicatorSpec(
        fn=ta.kc,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 100.0), 'scalar': (0.1, 10.0)},
        column_prefix='KCLe_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "KCUE": IndicatorSpec(
        fn=ta.kc,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 100.0), 'scalar': (0.1, 10.0)},
        column_prefix='KCUe_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "KST": IndicatorSpec(
        fn=ta.kst,
        inputs=('close',),
        params={'signal': (1.0, 50.0), 'roc1': (1.0, 50.0), 'roc2': (2.0, 100.0), 'roc3': (5.0, 150.0), 'roc4': (10.0, 200.0), 'sma1': (1.0, 50.0), 'sma2': (2.0, 100.0), 'sma3': (5.0, 150.0), 'sma4': (10.0, 200.0), 'drift': (0.0, 1.0)},
        column_prefix='KST_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "KSTS": IndicatorSpec(
        fn=ta.kst,
        inputs=('close',),
        params={'signal': (1.0, 50.0), 'roc1': (1.0, 50.0), 'roc2': (2.0, 100.0), 'roc3': (5.0, 150.0), 'roc4': (10.0, 200.0), 'sma1': (1.0, 50.0), 'sma2': (2.0, 100.0), 'sma3': (5.0, 150.0), 'sma4': (10.0, 200.0), 'drift': (0.0, 1.0)},
        column_prefix='KSTs_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "KURTOSIS": IndicatorSpec(
        fn=ta.kurtosis,
        inputs=('close',),
        params={'length': (2.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "KVO": IndicatorSpec(
        fn=ta.kvo,
        inputs=('high', 'low', 'close', 'volume'),
        params={'fast': (2.0, 50.0), 'slow': (10.0, 100.0), 'signal': (1.0, 50.0), 'drift': (0.0, 1.0)},
        column_prefix='KVO_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "KVOS": IndicatorSpec(
        fn=ta.kvo,
        inputs=('high', 'low', 'close', 'volume'),
        params={'fast': (2.0, 50.0), 'slow': (10.0, 100.0), 'signal': (1.0, 50.0), 'drift': (0.0, 1.0)},
        column_prefix='KVOs_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "LINREG": IndicatorSpec(
        fn=ta.linreg,
        inputs=('close',),
        params={'length': (2.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "LOG_RETURN": IndicatorSpec(
        fn=ta.log_return,
        inputs=('close',),
        params={'length': (1.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "LOW_Z": IndicatorSpec(
        fn=ta.cdl_z,
        inputs=('open', 'high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'ddof': (0.0, 2.0)},
        column_prefix='low_Z_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "MAD": IndicatorSpec(
        fn=ta.mad,
        inputs=('close',),
        params={'length': (2.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "MAMA": IndicatorSpec(
        fn=ta.mama,
        inputs=('close',),
        params={'fastlimit': (0.01, 1.0), 'slowlimit': (0.01, 1.0), 'prenan': (0.0, 1.0)},
        column_prefix='MAMA_',
        cross_check={'type': 'greater_than', 'left': 'fastlimit', 'right': 'slowlimit'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "MASSI": IndicatorSpec(
        fn=ta.massi,
        inputs=('high', 'low'),
        params={'fast': (2.0, 50.0), 'slow': (10.0, 100.0)},
        column_prefix=None,
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "MCGD": IndicatorSpec(
        fn=ta.mcgd,
        inputs=('close',),
        params={'length': (2.0, 100.0), 'c': (0.01, 1.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "MEDIAN": IndicatorSpec(
        fn=ta.median,
        inputs=('close',),
        params={'length': (2.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "MIDPOINT": IndicatorSpec(
        fn=ta.midpoint,
        inputs=('close',),
        params={'length': (2.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "MIDPRICE": IndicatorSpec(
        fn=ta.midprice,
        inputs=('high', 'low'),
        params={'length': (2.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "NVI": IndicatorSpec(
        fn=ta.nvi,
        inputs=('close', 'volume'),
        params={'length': (2.0, 500.0), 'initial': (1000.0, 1000000.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "OHLC4": IndicatorSpec(
        fn=ta.ohlc4,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "OPEN_Z": IndicatorSpec(
        fn=ta.cdl_z,
        inputs=('open', 'high', 'low', 'close'),
        params={'length': (2.0, 500.0), 'ddof': (0.0, 2.0)},
        column_prefix='open_Z_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PDIST": IndicatorSpec(
        fn=ta.pdist,
        inputs=('open', 'high', 'low', 'close'),
        params={'drift': (0.0, 5.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PERCENT_RETURN": IndicatorSpec(
        fn=ta.percent_return,
        inputs=('close',),
        params={'length': (1.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PGO": IndicatorSpec(
        fn=ta.pgo,
        inputs=('high', 'low', 'close'),
        params={'length': (2.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PIVOTS_TRAD_D_P": IndicatorSpec(
        fn=ta.pivots,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='PIVOTS_TRAD_D_P',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PIVOTS_TRAD_D_R1": IndicatorSpec(
        fn=ta.pivots,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='PIVOTS_TRAD_D_R1',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PIVOTS_TRAD_D_R2": IndicatorSpec(
        fn=ta.pivots,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='PIVOTS_TRAD_D_R2',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PIVOTS_TRAD_D_R3": IndicatorSpec(
        fn=ta.pivots,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='PIVOTS_TRAD_D_R3',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PIVOTS_TRAD_D_R4": IndicatorSpec(
        fn=ta.pivots,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='PIVOTS_TRAD_D_R4',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PIVOTS_TRAD_D_S1": IndicatorSpec(
        fn=ta.pivots,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='PIVOTS_TRAD_D_S1',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PIVOTS_TRAD_D_S2": IndicatorSpec(
        fn=ta.pivots,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='PIVOTS_TRAD_D_S2',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PIVOTS_TRAD_D_S3": IndicatorSpec(
        fn=ta.pivots,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='PIVOTS_TRAD_D_S3',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PIVOTS_TRAD_D_S4": IndicatorSpec(
        fn=ta.pivots,
        inputs=('open', 'high', 'low', 'close'),
        params={},
        column_prefix='PIVOTS_TRAD_D_S4',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PPO": IndicatorSpec(
        fn=ta.ppo,
        inputs=('close',),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 300.0), 'signal': (2.0, 100.0), 'scalar': (1.0, 1000.0)},
        column_prefix='PPO_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "PPOH": IndicatorSpec(
        fn=ta.ppo,
        inputs=('close',),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 300.0), 'signal': (2.0, 100.0), 'scalar': (1.0, 1000.0)},
        column_prefix='PPOh_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PPOS": IndicatorSpec(
        fn=ta.ppo,
        inputs=('close',),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 300.0), 'signal': (2.0, 100.0), 'scalar': (1.0, 1000.0)},
        column_prefix='PPOs_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PSARAF_0.": IndicatorSpec(
        fn=ta.psar,
        inputs=('high', 'low'),
        params={'af0': (0.001, 0.1), 'af': (0.001, 0.1), 'max_af': (0.01, 1.0)},
        column_prefix='PSARaf_0.',
        cross_check={'type': 'less_than', 'left': 'af0', 'right': 'max_af'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PSARL_0.": IndicatorSpec(
        fn=ta.psar,
        inputs=('high', 'low'),
        params={'af0': (0.001, 0.1), 'af': (0.001, 0.1), 'max_af': (0.01, 1.0)},
        column_prefix='PSARl_0.',
        cross_check={'type': 'less_than', 'left': 'af0', 'right': 'max_af'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PSARR_0.": IndicatorSpec(
        fn=ta.psar,
        inputs=('high', 'low'),
        params={'af0': (0.001, 0.1), 'af': (0.001, 0.1), 'max_af': (0.01, 1.0)},
        column_prefix='PSARr_0.',
        cross_check={'type': 'less_than', 'left': 'af0', 'right': 'max_af'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PSARS_0.": IndicatorSpec(
        fn=ta.psar,
        inputs=('high', 'low'),
        params={'af0': (0.001, 0.1), 'af': (0.001, 0.1), 'max_af': (0.01, 1.0)},
        column_prefix='PSARs_0.',
        cross_check={'type': 'less_than', 'left': 'af0', 'right': 'max_af'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "PSL": IndicatorSpec(
        fn=ta.psl,
        inputs=('close',),
        params={'length': (2.0, 500.0), 'scalar': (1.0, 1000.0), 'drift': (0.0, 5.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PVI": IndicatorSpec(
        fn=ta.pvi,
        inputs=('close', 'volume'),
        params={'length': (2.0, 500.0), 'initial': (1000.0, 1000000.0)},
        column_prefix='PVI',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "PVIE": IndicatorSpec(
        fn=ta.pvi,
        inputs=('close', 'volume'),
        params={'length': (2.0, 500.0), 'initial': (1000.0, 1000000.0)},
        column_prefix='PVIe_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PVO": IndicatorSpec(
        fn=ta.pvo,
        inputs=('volume',),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 300.0), 'signal': (2.0, 100.0), 'scalar': (1.0, 1000.0)},
        column_prefix='PVO_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "PVOH": IndicatorSpec(
        fn=ta.pvo,
        inputs=('volume',),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 300.0), 'signal': (2.0, 100.0), 'scalar': (1.0, 1000.0)},
        column_prefix='PVOh_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PVOL": IndicatorSpec(
        fn=ta.pvol,
        inputs=('close', 'volume'),
        params={},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PVOS": IndicatorSpec(
        fn=ta.pvo,
        inputs=('volume',),
        params={'fast': (2.0, 100.0), 'slow': (2.0, 300.0), 'signal': (2.0, 100.0), 'scalar': (1.0, 1000.0)},
        column_prefix='PVOs_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PVR": IndicatorSpec(
        fn=ta.pvr,
        inputs=('close', 'volume'),
        params={'drift': (0.0, 5.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PVT": IndicatorSpec(
        fn=ta.pvt,
        inputs=('close', 'volume'),
        params={'drift': (0.0, 5.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "PWMA": IndicatorSpec(
        fn=ta.pwma,
        inputs=('close',),
        params={'length': (2.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "QQE": IndicatorSpec(
        fn=ta.qqe,
        inputs=('close',),
        params={'length': (2.0, 500.0), 'smooth': (2.0, 100.0), 'factor': (0.5, 10.0), 'drift': (0.0, 5.0)},
        column_prefix='QQE_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "QQEL": IndicatorSpec(
        fn=ta.qqe,
        inputs=('close',),
        params={'length': (2.0, 500.0), 'smooth': (2.0, 100.0), 'factor': (0.5, 10.0), 'drift': (0.0, 5.0)},
        column_prefix='QQEl_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "QQES": IndicatorSpec(
        fn=ta.qqe,
        inputs=('close',),
        params={'length': (2.0, 500.0), 'smooth': (2.0, 100.0), 'factor': (0.5, 10.0), 'drift': (0.0, 5.0)},
        column_prefix='QQEs_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "QSTICK": IndicatorSpec(
        fn=ta.qstick,
        inputs=('open', 'close'),
        params={'length': (2.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "QUANTILE": IndicatorSpec(
        fn=ta.quantile,
        inputs=('close',),
        params={'length': (2.0, 500.0), 'q': (0.0, 1.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "REFLEX": IndicatorSpec(
        fn=ta.reflex,
        inputs=('close',),
        params={'length': (2.0, 500.0), 'smooth': (2.0, 100.0), 'alpha': (0.0, 1.0), 'pi': (3.1, 3.2), 'sqrt2': (1.4, 1.5)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "RMA": IndicatorSpec(
        fn=ta.rma,
        inputs=('close',),
        params={'length': (2.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "RSX": IndicatorSpec(
        fn=ta.rsx,
        inputs=('close',),
        params={'length': (2.0, 500.0), 'drift': (0.0, 5.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "RVI": IndicatorSpec(
        fn=ta.rvi,
        inputs=('close',),
        params={'length': (1.0, 100.0), 'scalar': (0.1, 100.0), 'drift': (0.0, 5.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "RWIH": IndicatorSpec(
        fn=ta.rwi,
        inputs=('high', 'low', 'close'),
        params={'length': (1.0, 100.0), 'drift': (0.0, 5.0)},
        column_prefix='RWIh_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "RWIL": IndicatorSpec(
        fn=ta.rwi,
        inputs=('high', 'low', 'close'),
        params={'length': (1.0, 100.0), 'drift': (0.0, 5.0)},
        column_prefix='RWIl_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "SINWMA": IndicatorSpec(
        fn=ta.sinwma,
        inputs=('close',),
        params={'length': (1.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "SKEW": IndicatorSpec(
        fn=ta.skew,
        inputs=('close',),
        params={'length': (3.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "SLOPE": IndicatorSpec(
        fn=ta.slope,
        inputs=('close',),
        params={'length': (1.0, 500.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "SMI": IndicatorSpec(
        fn=ta.smi,
        inputs=('close',),
        params={'fast': (1.0, 50.0), 'slow': (1.0, 200.0), 'signal': (1.0, 50.0), 'scalar': (0.1, 100.0)},
        column_prefix='SMI_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "SMIO": IndicatorSpec(
        fn=ta.smi,
        inputs=('close',),
        params={'fast': (1.0, 50.0), 'slow': (1.0, 200.0), 'signal': (1.0, 50.0), 'scalar': (0.1, 100.0)},
        column_prefix='SMIo_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "SMIS": IndicatorSpec(
        fn=ta.smi,
        inputs=('close',),
        params={'fast': (1.0, 50.0), 'slow': (1.0, 200.0), 'signal': (1.0, 50.0), 'scalar': (0.1, 100.0)},
        column_prefix='SMIs_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "SSF": IndicatorSpec(
        fn=ta.ssf,
        inputs=('close',),
        params={'length': (1.0, 500.0), 'pi': (3.1, 3.2), 'sqrt2': (1.4, 1.5)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "SSF3": IndicatorSpec(
        fn=ta.ssf3,
        inputs=('close',),
        params={'length': (1.0, 500.0), 'pi': (3.1, 3.2), 'sqrt3': (1.7, 1.8)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "STC": IndicatorSpec(
        fn=ta.stc,
        inputs=('close',),
        params={'tc_length': (1.0, 100.0), 'fast': (1.0, 50.0), 'slow': (1.0, 200.0), 'factor': (0.1, 1.0)},
        column_prefix='STC_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "STCMACD": IndicatorSpec(
        fn=ta.stc,
        inputs=('close',),
        params={'tc_length': (1.0, 100.0), 'fast': (1.0, 50.0), 'slow': (1.0, 200.0), 'factor': (0.1, 1.0)},
        column_prefix='STCmacd_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "STCSTOCH": IndicatorSpec(
        fn=ta.stc,
        inputs=('close',),
        params={'tc_length': (1.0, 100.0), 'fast': (1.0, 50.0), 'slow': (1.0, 200.0), 'factor': (0.1, 1.0)},
        column_prefix='STCstoch_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "STDEV": IndicatorSpec(
        fn=ta.stdev,
        inputs=('close',),
        params={'length': (1.0, 500.0), 'ddof': (0.0, 2.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "SUPERT": IndicatorSpec(
        fn=ta.supertrend,
        inputs=('high', 'low', 'close'),
        params={'length': (1.0, 100.0), 'atr_length': (1.0, 100.0), 'multiplier': (0.1, 10.0)},
        column_prefix='SUPERT_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "SUPERTD": IndicatorSpec(
        fn=ta.supertrend,
        inputs=('high', 'low', 'close'),
        params={'length': (1.0, 100.0), 'atr_length': (1.0, 100.0), 'multiplier': (0.1, 10.0)},
        column_prefix='SUPERTd_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "SUPERTL": IndicatorSpec(
        fn=ta.supertrend,
        inputs=('high', 'low', 'close'),
        params={'length': (1.0, 100.0), 'atr_length': (1.0, 100.0), 'multiplier': (0.1, 10.0)},
        column_prefix='SUPERTl_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "SUPERTS": IndicatorSpec(
        fn=ta.supertrend,
        inputs=('high', 'low', 'close'),
        params={'length': (1.0, 100.0), 'atr_length': (1.0, 100.0), 'multiplier': (0.1, 10.0)},
        column_prefix='SUPERTs_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "THERMO": IndicatorSpec(
        fn=ta.thermo,
        inputs=('high', 'low'),
        params={'length': (5.0, 100.0), 'long': (1.0, 200.0), 'short': (1.0, 200.0), 'drift': (0.0, 5.0)},
        column_prefix='THERMO_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "THERMOL": IndicatorSpec(
        fn=ta.thermo,
        inputs=('high', 'low'),
        params={'length': (5.0, 100.0), 'long': (1.0, 200.0), 'short': (1.0, 200.0), 'drift': (0.0, 5.0)},
        column_prefix='THERMOl_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "THERMOMA": IndicatorSpec(
        fn=ta.thermo,
        inputs=('high', 'low'),
        params={'length': (5.0, 100.0), 'long': (1.0, 200.0), 'short': (1.0, 200.0), 'drift': (0.0, 5.0)},
        column_prefix='THERMOma_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "THERMOS": IndicatorSpec(
        fn=ta.thermo,
        inputs=('high', 'low'),
        params={'length': (5.0, 100.0), 'long': (1.0, 200.0), 'short': (1.0, 200.0), 'drift': (0.0, 5.0)},
        column_prefix='THERMOs_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "TMO": IndicatorSpec(
        fn=ta.tmo,
        inputs=('open', 'close'),
        params={'tmo_length': (5.0, 100.0), 'calc_length': (2.0, 50.0), 'smooth_length': (2.0, 50.0)},
        column_prefix='TMO_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "TMOM": IndicatorSpec(
        fn=ta.tmo,
        inputs=('open', 'close'),
        params={'tmo_length': (5.0, 100.0), 'calc_length': (2.0, 50.0), 'smooth_length': (2.0, 50.0)},
        column_prefix='TMOM_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "TMOMS": IndicatorSpec(
        fn=ta.tmo,
        inputs=('open', 'close'),
        params={'tmo_length': (5.0, 100.0), 'calc_length': (2.0, 50.0), 'smooth_length': (2.0, 50.0)},
        column_prefix='TMOMs_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "TMOS": IndicatorSpec(
        fn=ta.tmo,
        inputs=('open', 'close'),
        params={'tmo_length': (5.0, 100.0), 'calc_length': (2.0, 50.0), 'smooth_length': (2.0, 50.0)},
        column_prefix='TMOs_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "TOS_STDEVALL": IndicatorSpec(
        fn=ta.tos_stdevall,
        inputs=('close',),
        params={'length': (2.0, 200.0), 'ddof': (0.0, 2.0)},
        column_prefix='TOS_STDEVALL_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "TRENDFLEX": IndicatorSpec(
        fn=ta.trendflex,
        inputs=('close',),
        params={'length': (5.0, 100.0), 'smooth': (1.0, 50.0), 'alpha': (0.1, 1.0), 'pi': (2.5, 3.5), 'sqrt2': (1.2, 1.5)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "TRIMA": IndicatorSpec(
        fn=ta.trima,
        inputs=('close',),
        params={'length': (2.0, 200.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "TRIX": IndicatorSpec(
        fn=ta.trix,
        inputs=('close',),
        params={'length': (5.0, 100.0), 'signal': (2.0, 50.0), 'scalar': (1.0, 1000.0), 'drift': (0.0, 5.0)},
        column_prefix='TRIX_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "TRIXS": IndicatorSpec(
        fn=ta.trix,
        inputs=('close',),
        params={'length': (5.0, 100.0), 'signal': (2.0, 50.0), 'scalar': (1.0, 1000.0), 'drift': (0.0, 5.0)},
        column_prefix='TRIXs_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "TSI": IndicatorSpec(
        fn=ta.tsi,
        inputs=('close',),
        params={'fast': (2.0, 30.0), 'slow': (10.0, 100.0), 'signal': (2.0, 50.0), 'scalar': (1.0, 1000.0), 'drift': (0.0, 5.0)},
        column_prefix='TSI_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "TSIS": IndicatorSpec(
        fn=ta.tsi,
        inputs=('close',),
        params={'fast': (2.0, 30.0), 'slow': (10.0, 100.0), 'signal': (2.0, 50.0), 'scalar': (1.0, 1000.0), 'drift': (0.0, 5.0)},
        column_prefix='TSIs_',
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'slow'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "TSV": IndicatorSpec(
        fn=ta.tsv,
        inputs=('close', 'volume'),
        params={'length': (2.0, 100.0), 'signal': (2.0, 50.0), 'drift': (0.0, 5.0)},
        column_prefix='TSV_',
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "TSVR": IndicatorSpec(
        fn=ta.tsv,
        inputs=('close', 'volume'),
        params={'length': (2.0, 100.0), 'signal': (2.0, 50.0), 'drift': (0.0, 5.0)},
        column_prefix='TSVr_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "TSVS": IndicatorSpec(
        fn=ta.tsv,
        inputs=('close', 'volume'),
        params={'length': (2.0, 100.0), 'signal': (2.0, 50.0), 'drift': (0.0, 5.0)},
        column_prefix='TSVs_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "UI": IndicatorSpec(
        fn=ta.ui,
        inputs=('close',),
        params={'length': (5.0, 200.0), 'scalar': (1.0, 1000.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "UO": IndicatorSpec(
        fn=ta.uo,
        inputs=('high', 'low', 'close'),
        params={'fast': (2.0, 20.0), 'medium': (5.0, 50.0), 'slow': (20.0, 200.0), 'fast_w': (0.1, 10.0), 'medium_w': (0.1, 10.0), 'slow_w': (0.1, 10.0), 'drift': (0.0, 5.0)},
        column_prefix=None,
        cross_check={'type': 'less_than', 'left': 'fast', 'right': 'medium'},
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "VARIANCE": IndicatorSpec(
        fn=ta.variance,
        inputs=('close',),
        params={'length': (2.0, 200.0), 'ddof': (0.0, 2.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "VHF": IndicatorSpec(
        fn=ta.vhf,
        inputs=('close',),
        params={'length': (5.0, 200.0), 'drift': (0.0, 5.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "VHM": IndicatorSpec(
        fn=ta.vhm,
        inputs=('volume',),
        params={'length': (5.0, 100.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "VIDYA": IndicatorSpec(
        fn=ta.vidya,
        inputs=('close',),
        params={'length': (2.0, 200.0), 'drift': (0.0, 5.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=False,
        verified_on=None,
        lib_version=None,
    ),
    "VTXM": IndicatorSpec(
        fn=ta.vortex,
        inputs=('high', 'low', 'close'),
        params={'length': (5.0, 200.0), 'drift': (0.0, 5.0)},
        column_prefix='VTXM_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "VTXP": IndicatorSpec(
        fn=ta.vortex,
        inputs=('high', 'low', 'close'),
        params={'length': (5.0, 200.0), 'drift': (0.0, 5.0)},
        column_prefix='VTXP_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "VWMA": IndicatorSpec(
        fn=ta.vwma,
        inputs=('close', 'volume'),
        params={'length': (2.0, 200.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "WCP": IndicatorSpec(
        fn=ta.wcp,
        inputs=('high', 'low', 'close'),
        params={},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ZIGZAGD": IndicatorSpec(
        fn=ta.zigzag,
        inputs=('high', 'low'),
        params={'legs': (2.0, 20.0), 'deviation': (0.1, 100.0)},
        column_prefix='ZIGZAGd_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ZIGZAGS": IndicatorSpec(
        fn=ta.zigzag,
        inputs=('high', 'low'),
        params={'legs': (2.0, 20.0), 'deviation': (0.1, 100.0)},
        column_prefix='ZIGZAGs_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ZIGZAGV": IndicatorSpec(
        fn=ta.zigzag,
        inputs=('high', 'low'),
        params={'legs': (2.0, 20.0), 'deviation': (0.1, 100.0)},
        column_prefix='ZIGZAGv_',
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ZLMA": IndicatorSpec(
        fn=ta.zlma,
        inputs=('close',),
        params={'length': (2.0, 200.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
    "ZSCORE": IndicatorSpec(
        fn=ta.zscore,
        inputs=('close',),
        params={'length': (2.0, 200.0), 'std': (0.5, 5.0)},
        column_prefix=None,
        cross_check=None,
        tier="extended",
        verified=True,
        verified_on=date(2026, 8, 2),
        lib_version='0.4.71b0',
    ),
}
