"""stage 5: agentic core schema

Revision ID: 0b150c55683b
Revises: ddb03ccb1cec
Create Date: 2026-08-19 17:39:04.193324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '0b150c55683b'
down_revision: Union[str, Sequence[str], None] = 'ddb03ccb1cec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enabled once already, manually, to verify the source-built extension
    # actually works before trusting it in a migration (see
    # docs/explanations/stage-5/step-01-*) -- IF NOT EXISTS makes this call
    # idempotent, so it's included here too for reproducibility: a fresh
    # environment running this migration gets the same result.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mandate_text', sa.Text(), nullable=False),
    sa.Column('charter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corpus_papers',
    sa.Column('arxiv_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('raw_path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('arxiv_id')
    )
    op.create_table('corpus_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.String(length=32), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['corpus_papers.arxiv_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_chunks_paper_id'), 'corpus_chunks', ['paper_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('charter_id', sa.String(length=36), nullable=False),
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction', sa.Text(), nullable=False),
    sa.Column('falsification_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grounding_tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charter_id'], ['charters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_charter_id'), 'hypotheses', ['charter_id'], unique=False)
    op.create_table('study_designs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('design', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_designs_hypothesis_id'), 'study_designs', ['hypothesis_id'], unique=False)
    op.create_table('study_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('study_design_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['study_design_id'], ['study_designs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_runs_hypothesis_id'), 'study_runs', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_study_runs_study_design_id'), 'study_runs', ['study_design_id'], unique=False)
    op.create_table('tool_call_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('study_run_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_error', sa.Boolean(), nullable=False),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_traces_study_run_id'), 'tool_call_traces', ['study_run_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('study_run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hypothesis_count_under_charter', sa.Integer(), nullable=False),
    sa.Column('corrected_significance_threshold', sa.Float(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_run_id'], ['study_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_study_run_id'), 'verdicts', ['study_run_id'], unique=False)
    op.create_table('scoreboard_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('verdict_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoreboard_entries_verdict_id'), 'scoreboard_entries', ['verdict_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Deliberately not dropping the vector extension here -- it's lower
    # blast-radius to leave an unused extension enabled than to drop
    # something with a wider footprint than this migration's own tables.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoreboard_entries_verdict_id'), table_name='scoreboard_entries')
    op.drop_table('scoreboard_entries')
    op.drop_index(op.f('ix_verdicts_study_run_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_tool_call_traces_study_run_id'), table_name='tool_call_traces')
    op.drop_table('tool_call_traces')
    op.drop_index(op.f('ix_study_runs_study_design_id'), table_name='study_runs')
    op.drop_index(op.f('ix_study_runs_hypothesis_id'), table_name='study_runs')
    op.drop_table('study_runs')
    op.drop_index(op.f('ix_study_designs_hypothesis_id'), table_name='study_designs')
    op.drop_table('study_designs')
    op.drop_index(op.f('ix_hypotheses_charter_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_corpus_chunks_paper_id'), table_name='corpus_chunks')
    op.drop_table('corpus_chunks')
    op.drop_table('corpus_papers')
    op.drop_table('charters')
    # ### end Alembic commands ###
