"""charter correction chain

Revision ID: 1497a09ac6e8
Revises: aaa61daf9d89
Create Date: 2026-09-01 19:29:02.875428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1497a09ac6e8'
down_revision: Union[str, Sequence[str], None] = 'aaa61daf9d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('charters', sa.Column('parent_charter_id', sa.String(length=36), nullable=True))
    # server_default added to the autogenerated line, deliberately -- same
    # fix as ac225385b472 (window_index on tool_call_traces), for the same
    # reason: autogenerate produced NOT NULL with no default, which only
    # works on an empty table. The real charters table already has rows by
    # the time this runs, so backfilling every existing row to round 0 (the
    # correct value -- they all predate the correction feature, so none of
    # them are corrections) is required, not optional.
    op.add_column('charters', sa.Column('correction_round', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('charters', sa.Column('correction_text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_charters_parent_charter_id'), 'charters', ['parent_charter_id'], unique=False)
    op.create_foreign_key(None, 'charters', 'charters', ['parent_charter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charters', type_='foreignkey')
    op.drop_index(op.f('ix_charters_parent_charter_id'), table_name='charters')
    op.drop_column('charters', 'correction_text')
    op.drop_column('charters', 'correction_round')
    op.drop_column('charters', 'parent_charter_id')
    # ### end Alembic commands ###
