"""stage 5: corpus_papers uses a universal id, not arxiv_id

Revision ID: 401a5c77cf08
Revises: 0b150c55683b
Create Date: 2026-08-22 15:13:59.829112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401a5c77cf08'
down_revision: Union[str, Sequence[str], None] = '0b150c55683b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate produced this as: drop the arxiv_id PK column, add a plain
    # (non-PK) id column, then create the FK straight to it -- Postgres
    # rejects an FK whose referenced column has no unique/PK constraint, so
    # that ordering would fail outright. Reordered by hand: add the new
    # corpus_papers columns and drop the old one first, explicitly make id
    # the new primary key, and only then create the FK against it.
    op.alter_column('corpus_chunks', 'paper_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_constraint(op.f('corpus_chunks_paper_id_fkey'), 'corpus_chunks', type_='foreignkey')
    op.add_column('corpus_papers', sa.Column('id', sa.String(length=64), nullable=False))
    op.add_column('corpus_papers', sa.Column('fetch_path', sa.String(length=16), nullable=False))
    op.drop_column('corpus_papers', 'arxiv_id')
    op.create_primary_key('corpus_papers_pkey', 'corpus_papers', ['id'])
    op.create_foreign_key(None, 'corpus_chunks', 'corpus_papers', ['paper_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'corpus_chunks', type_='foreignkey')
    op.drop_constraint('corpus_papers_pkey', 'corpus_papers', type_='primary')
    op.add_column('corpus_papers', sa.Column('arxiv_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_primary_key('corpus_papers_pkey', 'corpus_papers', ['arxiv_id'])
    op.drop_column('corpus_papers', 'fetch_path')
    op.drop_column('corpus_papers', 'id')
    op.create_foreign_key(op.f('corpus_chunks_paper_id_fkey'), 'corpus_chunks', 'corpus_papers', ['paper_id'], ['arxiv_id'])
    op.alter_column('corpus_chunks', 'paper_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
