"""verdict caveats and study_run failure_reason

Revision ID: aaa61daf9d89
Revises: ac225385b472
Create Date: 2026-08-24 21:47:35.198749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaa61daf9d89'
down_revision: Union[str, Sequence[str], None] = 'ac225385b472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_runs', sa.Column('failure_reason', sa.Text(), nullable=True))
    # server_default added to the autogenerated line, same fix as migration
    # ac225385b472's window_index column: autogenerate emits NOT NULL with no
    # default, which succeeds only because verdicts happens to be empty right
    # now and fails outright against any populated database.
    op.add_column(
        'verdicts',
        sa.Column('caveats', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verdicts', 'caveats')
    op.drop_column('study_runs', 'failure_reason')
    # ### end Alembic commands ###
