"""add window_index to tool_call_traces

Revision ID: ac225385b472
Revises: 401a5c77cf08
Create Date: 2026-08-23 00:22:07.763271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac225385b472'
down_revision: Union[str, Sequence[str], None] = '401a5c77cf08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default added to the autogenerated line, deliberately.
    # Autogenerate produced a NOT NULL column with no default, which works
    # only because tool_call_traces happens to be empty right now (Component
    # 6 is the first code that writes to it). Against any populated database
    # that statement fails outright -- Postgres cannot backfill NOT NULL
    # without a default. Keeping the default means this migration is
    # correct regardless of when it runs.
    op.add_column(
        'tool_call_traces',
        sa.Column('window_index', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_call_traces', 'window_index')
    # ### end Alembic commands ###
